# Generated by Django 2.2.5 on 2019-09-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['site', 'url', 'year', 'month', 'day', 'hour']},
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('site', 'url', 'year', 'month', 'day', 'hour')},
        ),
    ]
