# Generated by Django 2.2.5 on 2021-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20190925_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
